import { setCorsHeaders } from "./_lib/cors.js";
import { saveCatalog } from "./_lib/catalogStore.js";

function id(v){return String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");}
function admin(req,res){const t=process.env.ADMIN_API_TOKEN||process.env.ADMIN_TOKEN||"";if(!t)return true;const s=req.headers["x-admin-token"]||req.headers.authorization?.replace(/^Bearer\s+/i,"");if(s===t)return true;res.status(401).json({error:"Unauthorized."});return false;}
function linePending(){return [{id:"import-pending",name:"Import Pending",description:"Catalog saved. Extraction will add real lines.",doors:[],finishes:[],species:[]}];}
function aristoLines(brand){const doors=["Benton","Brellin","Briarcliff II","Durham","Ellis","Glyn","Lillian","Maddox","Quill","Sinclair","Teagan","Winstead"].map(n=>({id:id(n),label:n,value:brand+" "+n+" cabinet door style",image:"",swatch:"",desc:"Cabinet door style"}));const finishes=["PureStyle White","White","Frost","Stone Gray","Flagstone","Burlap","Sarsaparilla","Colada","Mythic Blue","Sage","Natural","Cafe","Umber","Cocoa","Autumn Brown","Flagstone Stain"].map(n=>({id:id(n),label:n,value:brand+" "+n+" cabinet finish",image:"",swatch:"",desc:"Cabinet finish"}));return [{id:"door-selection-guide",name:"Door Selection Guide",description:"Door styles and finishes.",doors,finishes,species:["Birch","Maple","Oak","Thermofoil","PureStyle"]}];}
function fromBody(body={}){const sourceUrl=String(body.sourceUrl||body.catalogUrl||body.url||"").trim();const name=String(body.name||"Imported Catalog").trim();const catalogId=id(body.catalogId||name);if(!catalogId)throw new Error("Manufacturer name is required.");const isAristo=/aristo|aristocraft/i.test(name+" "+sourceUrl);return{catalogId,name,version:String(body.version||new Date().toISOString().slice(0,10)),sourceType:sourceUrl?"url":"manual",sourceUrl,notes:"Unique supplier catalog. Multiple catalogs can be selected per customer.",manufacturers:[{id:id(name),name,sourceUrl,lines:isAristo?aristoLines(name):linePending()}]};}
export default async function handler(req,res){if(setCorsHeaders(req,res,"POST, OPTIONS"))return;res.setHeader("Cache-Control","no-store, max-age=0");if(req.method!=="POST")return res.status(405).json({error:"Method not allowed."});if(!admin(req,res))return;try{const catalog=await saveCatalog(fromBody(req.body||{}));return res.status(200).json({catalog,message:"Catalog saved."});}catch(e){return res.status(400).json({error:e?.message||"Catalog import failed."});}}
