import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

function cleanText(value, fallback = "-") {
  const text = String(value || "").trim();
  return text || fallback;
}

function escapeHtml(value) {
  return cleanText(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function getClientIp(req) {
  const forwarded = req.headers["x-forwarded-for"];
  if (typeof forwarded === "string" && forwarded.trim()) {
    return forwarded.split(",")[0].trim();
  }
  return req.socket?.remoteAddress || "-";
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const payload = req.body || {};

    // Simple spam trap. Leave this field hidden/empty in the website form.
    if (payload.website_confirm) {
      return res.status(200).json({ success: true });
    }

    const name = cleanText(payload.name || payload.customerName, "");
    const email = cleanText(payload.email || payload.customerEmail, "");
    const phone = cleanText(payload.phone || payload.customerPhone);
    const company = cleanText(payload.company || payload.companyName);
    const website = cleanText(payload.website || payload.companyWebsite);
    const plan = cleanText(payload.plan || payload.interest);
    const message = cleanText(payload.message || payload.notes);
    const page = cleanText(payload.page || payload.source || "Cabinet Visualizer website");

    if (!name) {
      return res.status(400).json({ error: "Please enter your name." });
    }

    if (!email || !email.includes("@")) {
      return res.status(400).json({ error: "Please enter a valid email address." });
    }

    const recipient = process.env.DEMO_REQUEST_EMAIL || "Dusty@cabinetvisualizer.com";

    const html = `
      <div style="font-family:Arial,sans-serif;line-height:1.5;color:#111827;">
        <h2 style="margin:0 0 12px;">New Cabinet Visualizer Demo Request</h2>
        <p><strong>Name:</strong> ${escapeHtml(name)}</p>
        <p><strong>Company:</strong> ${escapeHtml(company)}</p>
        <p><strong>Email:</strong> ${escapeHtml(email)}</p>
        <p><strong>Phone:</strong> ${escapeHtml(phone)}</p>
        <p><strong>Website:</strong> ${escapeHtml(website)}</p>
        <p><strong>Plan / Interest:</strong> ${escapeHtml(plan)}</p>
        <p><strong>Message:</strong><br>${escapeHtml(message).replace(/\n/g, "<br>")}</p>
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:18px 0;">
        <p><strong>Submitted From:</strong> ${escapeHtml(page)}</p>
        <p><strong>IP:</strong> ${escapeHtml(getClientIp(req))}</p>
        <p style="font-size:12px;color:#6b7280;margin-top:22px;">Generated by Cabinet Visualizer.</p>
      </div>
    `;

    const result = await resend.emails.send({
      from: "Cabinet Visualizer <leads@cabinetvisualizer.com>",
      to: [recipient],
      reply_to: email,
      subject: `New Demo Request | ${company !== "-" ? company : name}`,
      html
    });

    if (result.error) {
      return res.status(500).json({
        error: result.error.message || "Demo request email failed."
      });
    }

    return res.status(200).json({
      success: true,
      id: result.data?.id || null
    });
  } catch (error) {
    return res.status(500).json({
      error: error?.message || "Demo request email failed."
    });
  }
}
