import { Resend } from "resend";
import { getCustomer } from "./_lib/customerStore.js";

const resend = new Resend(process.env.RESEND_API_KEY);

function cleanText(value, fallback = "-") {
  const text = String(value || "").trim();
  return text || fallback;
}

function uniqueEmails(emails) {
  return Array.from(new Set(
    emails
      .map(function(email) { return String(email || "").trim(); })
      .filter(function(email) { return email && email.includes("@"); })
  ));
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const payload = req.body || {};
    const companyKey = cleanText(payload.companyKey, "");

    if (!companyKey) {
      return res.status(400).json({ error: "Missing company key." });
    }

    const company = await getCustomer(companyKey);

    if (!company) {
      return res.status(404).json({ error: "Company not found." });
    }

    if (company.status === "archived") {
      return res.status(403).json({ error: "This company is inactive." });
    }

    const kpmCopyEmail = process.env.LEAD_COPY_EMAIL || "dusty@jcabinetry.com";
    const companyEmail = company.email || company.contactEmail || company.branding?.email || company.branding?.contactEmail;
    const recipients = uniqueEmails([companyEmail, kpmCopyEmail]);

    if (!recipients.length) {
      return res.status(400).json({ error: "No lead recipient email is configured." });
    }

    const companyName = cleanText(company.companyName || payload.company);
    const customerName = cleanText(payload.customerName);
    const customerPhone = cleanText(payload.customerPhone);
    const customerEmail = cleanText(payload.customerEmail);
    const notes = cleanText(payload.notes);

    const html = `
      <div style="font-family:Arial,sans-serif;line-height:1.5;color:#111827;">
        <h2 style="margin:0 0 12px;">New Cabinet Visualizer Lead</h2>
        <p><strong>Company:</strong> ${companyName}</p>
        <p><strong>Name:</strong> ${customerName}</p>
        <p><strong>Phone:</strong> ${customerPhone}</p>
        <p><strong>Email:</strong> ${customerEmail}</p>
        <p><strong>Project Notes:</strong><br>${notes}</p>
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:18px 0;">
        <h3 style="margin:0 0 10px;">Selected Design Options</h3>
        <p><strong>Upper Color:</strong> ${cleanText(payload.upperColor)}</p>
        <p><strong>Base Cabinet Color:</strong> ${cleanText(payload.islandColor)}</p>
        <p><strong>Door Style:</strong> ${cleanText(payload.doorStyle)}</p>
        <p><strong>Hardware:</strong> ${cleanText(payload.hardware)}</p>
        <p><strong>Countertops:</strong> ${cleanText(payload.countertop)}</p>
        <p><strong>Backsplash:</strong> ${cleanText(payload.backsplash)}</p>
        <p><strong>Flooring:</strong> ${cleanText(payload.flooring)}</p>
        <p style="font-size:12px;color:#6b7280;margin-top:22px;">Generated by Cabinet Visualizer.</p>
      </div>
    `;

    const result = await resend.emails.send({
      from: "Cabinet Visualizer <leads@cabinetvisualizer.com>",
      to: recipients,
      subject: `New Visualizer Lead | ${companyName}`,
      html
    });

    if (result.error) {
      return res.status(500).json({
        error: result.error.message || "Lead email failed."
      });
    }

    return res.status(200).json({
      success: true,
      recipients,
      id: result.data?.id || null
    });
  } catch (error) {
    return res.status(500).json({
      error: error?.message || "Lead email failed."
    });
  }
}
